name: C/C++ CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Configure
      run: ./configure

    - name: Makefile
      run: make

    - name: Run main file on windows
      if: runner.os == 'Windows'
      run: .\main
    - name: Run main file on linux
      if: runner.os == 'Linux'
      run: ./main
    - name: Run main file on macOS
      if: runner.os == 'macOS'
      run: ./main

    - name: Run catch2 tests on windows
      if: runner.os == 'Windows'
      run: .\testes
    - name: Run catch2 tests on linux
      if: runner.os == 'Linux'
      run: ./testes
    - name: Run catch2 tests on macOS
      if: runner.os == 'macOS'
      run: ./testes